# Generated by Django 5.0.2 on 2024-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_display_name_user_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Suspended", "Suspended"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
