# Generated by Django 5.0.2 on 2024-03-02 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="owners",
        ),
        migrations.AddField(
            model_name="channel",
            name="managers",
            field=models.ManyToManyField(
                related_name="managed_channels", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_channels",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="subscribed_channels", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
