# Generated by Django 5.0.2 on 2024-03-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_remove_channel_managers_remove_channel_owner_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
        migrations.AlterField(
            model_name="channel",
            name="creators",
            field=models.ManyToManyField(to="channels.channelmember"),
        ),
        migrations.AlterField(
            model_name="channelmember",
            name="channel_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_members",
                to="channels.channel",
            ),
        ),
    ]
