# Generated by Django 5.0.2 on 2024-03-11 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0004_rename_links_link_alter_channel_creators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="channelmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channelmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
