# Generated by Django 5.0.3 on 2024-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0005_channel_updated_at_channelmember_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelmember",
            name="uid",
        ),
    ]
